config/routes.rb
Rails.application.routes.draw do
  resources :publications

  resources :members

end

app/models/member.rb
class Member < ActiveRecord::Base
  
  has_and_belongs_to_many :publications
  
  validates_presence_of :firstName
  validates_presence_of :lastName
  
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  
  has_and_belongs_to_many :members
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all.order(:lastname)
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @publications = @member.publications
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:lastName, :firstName, :position)
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @members     = Member.all
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @member      = Member.find(params[:member_id][:member_ids])
    @publication = Publication.new(publication_params)
    
    @publication.members << @member

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :author, :conferenceName, :location, :year, :member_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacultyDirectory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <thead>
    <tr>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.lastName %></td>
        <td><%= member.firstName %></td>
        <td><%= member.position %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lastname:</strong>
  <%= @member.lastName %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @member.firstName %>
</p>

<p>
  <strong>Position:</strong>
  <%= @member.position %>
</p>

<p>
  <strong>Publications: <ins><%= @publications.length %></ins></strong>
  <ul>
	<% if @publications.empty? %>
		<i>Nothing written, maybe a mistake.</i>
	<% end%>
	<% @publications.each do |publication| %>
		<ol><%= link_to publication[:title], publication_path(publication) %></ol>
	<% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br>
	<%= collection_select(:member_id, :member_ids, Member.all, :id, :lastName) %>
  </div>
  <div class="field">
    <%= f.label :conferenceName %><br>
    <%= f.text_field :conferenceName %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h1>Listing publications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Conferencename</th>
      <th>Location</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.title %></td>
        <td><%= publication.conferenceName %></td>
        <td><%= publication.location %></td>
        <td><%= publication.year %></td>
        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>

<p>
  <strong>Conferencename:</strong>
  <%= @publication.conferenceName %>
</p>

<p>
  <strong>Location:</strong>
  <%= @publication.location %>
</p>

<p>
  <strong>Year:</strong>
  <%= @publication.year %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>